### ISSUE TITLE
Issues with module settings

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/node_css#2]
Thanks for this interesting module! I've encountered a few issues regarding the module settings in version 1.x-1.0.1:

- In the Node CSS entry on the page `admin/modules`, there is no link to the settings page of the module.
- In the settings form at `admin/config/content/node_css`, under "Enable Node CSS for Content Types" it should be mentioned that the module is enabled for _all_ content types as long as no checkbox is ticked.
- After disabling the module for a content type, the (CSS generated) "Success" message on nodes of that type (see screenshot below) remains visible, so the CSS seems to stay active, even after clearing caches.

<img src="https://github.com/user-attachments/assets/0e066aa5-4f34-4342-876f-e059362c9c77" width=500>

**Comment by alanmels** [comment]
Thanks for suggestions. See the next PR.
