### ISSUE TITLE
CSS does not take immediate effect

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/node_css#3]
I love this module. Small issue:

I create a test page and leave the default css on the node. After saving the css changes are not visible and do not show up after clearing the cache. 

![image](https://github.com/user-attachments/assets/a43380a0-666c-4a1a-b9dc-c10a5516f750)

However, if I go to the edit page and then save the node again (without making any changes), the css is now in effect. 

![image](https://github.com/user-attachments/assets/617ec595-fcdc-4861-a98b-939cfc626e8f)

This could be very confusing to users.

**Comment by alanmels** [comment]
Thanks for spotting this. PR is coming in couple minutes.
