### ISSUE TITLE
IDEA: Hide CSS field in accordion?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/node_css#4]
Again, I love the module and appreciate it. This is just a suggestion.

The css field takes up a lot of space at the top of very node. 

I assume this is because of the goal to make this module very easy to use and to make sure this field is easy to find. I would prefer that it not take up so much real estate (space) at the top of the node edit form. 

Possible solutions:

1) Put this field into an accordion that remains highly visible at the top of the page, but is closed until opened. OR it could be open by default, but allow the user to close it until they need it again. 

2) Position it lower on the page (between tabs and "Save" button)?

3) Allow user to configure the positioning site wide?

**Comment by olafgrabienski** [comment]
Another option: Put it in a vertical tab.

**Comment by alanmels** [comment]
Thanks for nice suggestions. See the next release.
