### ISSUE TITLE
Allow user to disable or change default CSS 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/node_css#5]
Friendly suggestions:

I'm not seeing anyway to disable the default CSS rules once you have the module working. It's nice to have some default CSS there the first time. But, I think it would be nice if I did not have to delete or change it on every node.

It would also be nice if the user could change the default css for every node of a specific content type.

(I'll quit making suggestions now. Thanks for this module.)

I like that the CSS is stored in config and not the database.

**Comment by alanmels** [comment]
@stpaultim, the module had been rolled out quite raw as it was working for a specific use case, however I see lot's of room to improvement to cover all use cases. So keep coming with useful suggestions. 

Meanwhile, I'll see what can be changed to close this one.
